image: node:12.16.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - cd FYDCaseStudy-WebApp
  - npm install -g @angular/cli@6.2.1
  - npm install
  - ng build
  - mv dist/FYDCaseStudy-WebApp/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - pages